AWSTemplateFormatVersion: '2010-09-09'
Description: Déploiement automatique d'une app Streamlit sur EC2 via GitHub

Parameters:
  GitRepoURL:
    Type: String
    Default: https://github.com/longduongups/streamlit-breast-app.git
    Description: Lien GitHub 

Resources:
  StreamlitSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Autoriser HTTP pour Streamlit
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0

  StreamlitInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: mykey 
      ImageId: ami-0fc5d935ebf8bc3bc  # Ubuntu 22.04 LTS pour eu-west-3 (Paris)
      SecurityGroups:
        - !Ref StreamlitSecurityGroup
      Tags:
        - Key: Name
          Value: StreamlitApp
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y python3-pip git
          pip3 install streamlit pandas requests
          cd /home/ubuntu
          git clone ${GitRepoURL}
          REPO_NAME=$(basename ${GitRepoURL} .git)
          cd $REPO_NAME
          nohup streamlit run app_supabase.py --server.port 80 --server.enableCORS false &

Outputs:
  AppURL:
    Description: Lien vers l'application Streamlit déployée
    Value: !Sub "http://${StreamlitInstance.PublicIp}"
